initial_data_checklist = [
    {'description': 'Chegou desligado', 'checked': False},
    {'description': 'Cliente possibilita demais testes', 'checked': False},
    {'description': 'Alto falante estourado/chiando', 'checked': False},
    {'description': 'Sensor de proximidade', 'checked': False},
    {'description': 'Câmera frontal', 'checked': False},
    {'description': 'Câmera traseira', 'checked': False},
    {'description': 'Conector de carga"', 'checked': False},
    {'description': 'Microfone', 'checked': False},
    {'description': 'Rede e Wi-Fi', 'checked': False},
    {'description': 'Biometria', 'checked': False},
    {'description': 'Bateria inchada', 'checked': False},
    {'description': 'Touch Screen', 'checked': False},
    {'description': 'Tela', 'checked': False},
    {'description': 'Botão de volume/Power', 'checked': False},
    {'description': 'Biometria', 'checked': False},
    {'description': 'Botão Power', 'checked': False},
    {'description': 'Leitor biométrico', 'checked': False},
    {'description': 'Auto falante', 'checked': False},
    {'description': 'Auricular', 'checked': False},
    {'description': 'VibraCall', 'checked': False},
    {'description': 'Conector fone de ouvido', 'checked': False},
    {'description': 'Serviço prestado teve êxito', 'checked': False},
    {'description': 'Possui senha', 'checked': False},
]