# Generated by Django 5.2.4 on 2025-07-14 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=255, verbose_name='Aparelho')),
                ('defect', models.CharField(max_length=255, verbose_name='Defeito')),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('additional_info_exit', models.TextField(blank=True, null=True)),
                ('additional_description', models.TextField()),
                ('service_autorized', models.BooleanField(default=False)),
                ('service_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('service_initial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('missing_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Total')),
                ('shipping_date', models.DateTimeField(blank=True, null=True)),
                ('name_withdrawal', models.CharField(max_length=255, verbose_name='Defeito')),
                ('withdrawal_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('checked', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.checklist')),
            ],
        ),
    ]
