# Generated by Django 5.2.4 on 2025-07-14 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='missing_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor a receber'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_withdrawal',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome de quem retirou'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_initial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor de Entrada'),
        ),
    ]
