# Generated by Django 5.2.4 on 2025-07-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_missing_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
