# Generated by Django 5.2.4 on 2025-07-22 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_order_shipping_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_description',
            field=models.TextField(verbose_name='Serviço Prestado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_order', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='order',
            name='service_autorized',
            field=models.BooleanField(default=False, verbose_name='Serviço Autorizado'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de recebimento'),
        ),
        migrations.AlterField(
            model_name='order',
            name='withdrawal_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de retirada'),
        ),
    ]
