# Generated by Django 5.2.4 on 2025-07-30 00:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_created_by_alter_order_additional_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-shipping_date'], 'verbose_name': 'Ordem de Serviço', 'verbose_name_plural': 'Ordens de Serviço'},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by', 'shipping_date'], name='order_order_created_05e283_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by', 'service_autorized'], name='order_order_created_edb122_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_by', 'withdrawal_date'], name='order_order_created_285d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['service_autorized', 'withdrawal_date'], name='order_order_service_322e9d_idx'),
        ),
    ]
