# Generated by Django 5.2.4 on 2025-08-05 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additional_description',
            field=models.TextField(blank=True, null=True, verbose_name='Serviço Prestado'),
        ),
    ]
